(deftheme tsdh-dark-brusten
  "Created 2015-05-10.")

(custom-theme-set-faces
 'tsdh-dark-brusten
 '(compilation-mode-line-fail ((t (:foreground "red"))))
 '(compilation-mode-line-run ((t (:foreground "dark orange"))))
 '(compilation-mode-line-exit ((t (:foreground "sea green"))))
 '(dired-directory ((t (:inherit font-lock-function-name-face :weight bold))))
 '(header-line ((t (:inherit mode-line :inverse-video t))))
 ;; '(minibuffer-prompt ((t (:background "yellow" :foreground "medium blue" :box (:line-width -1 :color "red" :style released-button) :weight bold))))
 ;; '(mode-line ((t (:box (:line-width -1 :color "red" :style released-button) :family "DejaVu Sans"))))
 '(mode-line-inactive ((t (:inherit mode-line :foreground "gray"))))
 '(org-agenda-date ((t (:inherit org-agenda-structure))))
 '(org-agenda-date-today ((t (:inherit org-agenda-date :underline t))))
 '(org-agenda-date-weekend ((t (:inherit org-agenda-date :foreground "dark green"))))
 '(org-agenda-structure ((t (:foreground "SkyBlue" :weight bold))))
 '(org-hide ((t (:foreground "gray30"))))
 '(org-tag ((t (:weight bold))))
 '(outline-1 ((t (:inherit font-lock-function-name-face :weight bold))))
 '(outline-2 ((t (:inherit font-lock-variable-name-face :weight bold))))
 '(outline-3 ((t (:foreground "DodgerBlue"))))
 '(outline-4 ((t (:inherit font-lock-comment-face :weight bold))))
 '(outline-5 ((t (:inherit font-lock-type-face :weight bold))))
 '(outline-6 ((t (:inherit font-lock-constant-face :weight bold))))
 '(outline-7 ((t (:inherit font-lock-builtin-face :weight bold))))
 '(outline-8 ((t (:inherit font-lock-string-face :weight bold))))
 ;; '(region ((t (:height 1.05))))
 '(show-paren-match ((t (:height 1.1))))
 ;;'(show-paren-mismatch ((t (:background "red1" :foreground "black" :weight extra-bold :height 1.15))))
 ;;'(font-latex-math-face ((t (:foreground "burlywood" :weight normal :height 1.04))))
 '(font-latex-italic-face ((t (:inherit italic :foreground "#66999D" :hight 1.03))))
 '(font-latex-bold-face ((t (:inherit bold :foreground "OliveDrab4" :weight bold))))
 '(font-latex-sectioning-5-face ((t (:inherit variable-pitch :foreground "chocolate2" :weight bold))))
 '(font-latex-subscript-face ((t (:height 0.8))))
 '(font-latex-superscript-face ((t (:height 0.8))))
 '(font-lock-keyword-face ((t (:foreground "DodgerBlue"))))
 '(font-latex-sedate-face ((t (:inherit font-lock-function-name-face))))
 '(font-latex-warning-face ((t (:inherit bold :foreground "deep sky blue" :height 1.05))))
 '(font-lock-function-name-face ((t (:foreground "#DD6F48" ))))
 '(font-lock-comment-face ((t (:foreground "dark gray"))))
 '(font-lock-constant-face ((t (:foreground "OliveDrab4" :inherit italic))))
 '(org-level-3 ((t (:foreground "DodgerBlue" :weight bold))))
 '(org-special-keyword ((t (:foreground "navajo white" :weight thin))))
 '(org-date ((t (:background "gray15" :foreground "wheat" :underline t))))
 '(org-todo ((t (:background "gray10" :foreground "deep pink" :box (:line-width 1 :color "deep pink" :style released-button) :weight bold :height 1.1))))
 '(org-done ((t (:foreground "aquamarine" :slant oblique :weight bold))))
 '(default ((t (:background "gray22" :foreground "white smoke")))))

(provide-theme 'tsdh-dark-brusten)
